version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.6.0-spacy-de
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - ./app:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
  duckling:
    image: rasa/duckling:0.1.6.2
    restart: unless-stopped
# LD: it's not necessary that duckling expand it's port.
#    ports:
#      - 8000:8000