version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.1.3-spacy-de
    container_name: rasa
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - ./app:/app/
    links:
      - duckling
    command:
      - run
      - --enable-api
      - --cors
      - "*"
  duckling:
    image: rasa/duckling:0.1.6.5
    container_name: rasa-duckling
    restart: unless-stopped
# LD: it's not necessary that duckling expand it's port.
#    ports:
#      - 8000:8000

networks:
  default:
    external:
      name: beuthbot_network
