#!/bin/sh
set -x
set -u
set -e

function handle_file {
    local A_FILE="${1}.chatito"
    local TRAIN_FILE="${1}.json"

    npx chatito ./input/${A_FILE} \
        --format="rasa" \
        --outputPath="/app/output" \
        --trainingFileName="${TRAIN_FILE}" \

    python -m json.tool \
        /app/output/${TRAIN_FILE} > /app/data/${TRAIN_FILE}
}

handle_file mensa
handle_file weather
handle_file database
handle_file opening-hours

rm -rf "/app/output"
