#!/bin/sh
set -x
set -u
set -e

output_dir="/var/output"
data_dir="/app/data"

for file_path in ./input/*.chatito ;
do
  echo "file_path: ${file_path}"
  file_name="$(basename -- "${file_path}")"
  file_name="${file_name%.*}"
  train_file="${file_name}.json"
  test_file="${file_name}_testing.json"

  npx chatito ${file_path} \
    --format="rasa" \
    --outputPath="${output_dir}" \
    --trainingFileName="${train_file}" \
    --testingFileName="${test_file}"

    if [[ "${BEAUTIFY_JSON}" == "1" ]] ; then
      python -m json.tool ${output_dir}/${train_file} > ${data_dir}/${train_file}
    else
      cp ${output_dir}/${train_file} ${data_dir}/${train_file}
    fi
done
