version: '3.0'
services:
  chatito:
    build: chatito
    container_name: rasa-generate
    volumes:
      - ./app:/app
  training:
    image: rasa/rasa:1.6.0-spacy-de
    container_name: rasa-training
    volumes:
      - ./app:/app
    command:
      - train
      - nlu