# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: de

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 30
  - name: EntitySynonymMapper
  - name: DucklingEntityExtractor
    url: "http://duckling:8000"
    dimensions: ["time"]
    locale: "de_DE"
    timezone: "Europe/Berlin"
    timeout : 3
