# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: de

pipeline:
  - name: "WhitespaceTokenizer"
    case_sensitive: false
#  - name: "SpacyNLP"
#  - name: "SpacyTokenizer"
#  - name: "SpacyFeaturizer"
#  - name: "RegexFeaturizer"
#    return_sequence: true
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "EmbeddingIntentClassifier"
  - name: "DucklingHTTPExtractor"
    url: "http://duckling:8000"
    dimensions: ["time"]
    locale: "de_DE"
    timezone: "Europe/Berlin"
    timeout : 3