# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: de

pipeline:
    - name: "WhitespaceTokenizer"
      case_sensitive: false
    - name: "RegexFeaturizer"
    - name: "CRFEntityExtractor"
    - name: "EntitySynonymMapper"
    - name: "CountVectorsFeaturizer"
    - name: "CountVectorsFeaturizer"
      analyzer: "char_wb"
      min_ngram: 1
      max_ngram: 4
    - name: "EmbeddingIntentClassifier"
    - name: "DucklingHTTPExtractor"
      url: "http://duckling:8000"
      # see https://github.com/RasaHQ/duckling#supported-dimensions of a list of supported dimensions
      dimensions: ["Time", "Email", "Numeral", "PhoneNumber", "Distance", "Duration"]
      locale: "de_DE"
      timezone: "Europe/Berlin"
      timeout : 3
